name: dartloom_storage
description: Text, JSON, and database storage contracts for Dartloom applications.
version: 0.3.1
repository: https://github.com/wkzMagician/dartloom
homepage: https://github.com/wkzMagician/dartloom
issue_tracker: https://github.com/wkzMagician/dartloom/issues
topics:
  - flutter
  - dartloom
  - storage
environment:
  sdk: ^3.5.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
