import 'dart:convert';

import '../capabilities/capability_registry.dart';
import '../config/dartloom_config.dart';
import '../config/option_schema.dart';

String capabilityGlue(DartloomConfig config) {
  final enabled = config.enabledCapabilities;
  final hasSingleton = enabled.contains(Capability.singleton);
  final imports = <String>{
    "import 'package:dartloom_runtime/dartloom_runtime.dart';",
    "import 'package:flutter/foundation.dart';",
    "import 'package:flutter/widgets.dart';",
  };
  if (enabled.contains(Capability.settings)) {
    imports.add("import 'package:dartloom_settings/dartloom_settings.dart';");
  }
  if (enabled.contains(Capability.storage)) {
    imports.add("import 'package:dartloom_storage/dartloom_storage.dart';");
  }
  if (enabled.contains(Capability.logging)) {
    imports.add("import 'package:dartloom_logging/dartloom_logging.dart';");
  }
  if (enabled.contains(Capability.autostart)) {
    imports
      ..add("import 'dart:io';")
      ..add("import 'package:dartloom_autostart/dartloom_autostart.dart';");
  }
  if (enabled.contains(Capability.sync)) {
    imports
      ..add("import 'package:dartloom_sync/dartloom_sync.dart';")
      ..add(
          "import 'package:dartloom_sync_storage/dartloom_sync_storage.dart';")
      ..add(
          "import 'package:dartloom_sync_flutter/dartloom_sync_flutter.dart';")
      ..add(
          "import 'package:dartloom_sync_workmanager/dartloom_sync_workmanager.dart';");
  }
  if (enabled.contains(Capability.localization)) {
    imports
      ..add(
        "import 'package:dartloom_localization/dartloom_localization.dart';",
      )
      ..add(
        "import 'package:${config.app.name}/l10n/app_localizations.dart';",
      );
  }
  if (enabled.contains(Capability.resident)) {
    imports.add("import 'package:dartloom_resident/dartloom_resident.dart';");
  }
  if (enabled.contains(Capability.messaging)) {
    imports.add("import 'package:dartloom_messaging/dartloom_messaging.dart';");
  }
  if (enabled.contains(Capability.pairing)) {
    imports.add("import 'package:dartloom_pairing/dartloom_pairing.dart';");
  }
  if (enabled.contains(Capability.singleton)) {
    imports.add("import 'package:dartloom_singleton/dartloom_singleton.dart';");
  }
  final singleInstanceHook = hasSingleton
      ? '''    onInitialized: ensureSingleInstance
        ? (registration) async {
            if (registration.capability == 'singleton') {
              await Dartloom.get<SingleInstanceService>()
                  .ensureSingleInstance();
            }
          }
        : null,'''
      : '';
  for (final capability in config.capabilities.entries) {
    for (final instance in capability.value.values) {
      final metadata = CapabilityRegistry.implementation(
        capability.key,
        instance.implementation,
      );
      if (metadata != null) {
        if (instance.implementation == 'app_file_replica') continue;
        imports.add(
          "import 'package:${metadata.packageName}/${metadata.packageName}.dart';",
        );
      }
      if (capability.key == Capability.sync &&
          instance.backend?.implementation == 'webdav') {
        imports.add(
          "import 'package:dartloom_sync_webdav/dartloom_sync_webdav.dart';",
        );
      }
    }
  }

  final buffer = StringBuffer()
    ..writeln(
        '// Generated by Dartloom. This file is overwritten by project upgrade.')
    ..writeln(imports.join('\n'))
    ..writeln()
    ..writeln('Future<void> initializeDartloom({')
    ..writeln('  Map<String, DartloomFactory> customFactories = const {},')
    ..writeln('  DartloomStartupScope scope = DartloomStartupScope.foreground,')
    ..writeln('  bool ensureSingleInstance = false,')
    ..writeln('}) async {')
    ..writeln('  late final Map<String, DartloomFactory> factories;')
    ..writeln('  final officialFactories = <String, DartloomFactory>{');
  _writeOfficialFactories(buffer, config);
  buffer
    ..writeln('  };')
    ..writeln('  final collisions = officialFactories.keys.toSet()')
    ..writeln('      .intersection(customFactories.keys.toSet());')
    ..writeln('  if (collisions.isNotEmpty) {')
    ..writeln(
        "    throw DartloomException('custom factories cannot replace official factories: \$collisions');")
    ..writeln('  }')
    ..writeln('  factories = {...officialFactories, ...customFactories};')
    ..writeln('  await Dartloom.initialize(')
    ..writeln('    <DartloomRegistration<Object>>[');
  _writeRegistrations(buffer, config);
  buffer
    ..writeln('    ],')
    ..writeln('    factories: factories,')
    ..writeln('    scope: scope,')
    ..writeln(singleInstanceHook)
    ..writeln('  );')
    ..writeln('}')
    ..writeln()
    ..writeln('Future<void> disposeDartloom() => Dartloom.dispose();')
    ..writeln();
  if (enabled.contains(Capability.sync)) {
    buffer
      ..writeln("@pragma('vm:entry-point')")
      ..writeln('void dartloomSyncCallbackDispatcher() {')
      ..writeln('  executeDartloomSyncWorker((instanceName) async {')
      ..writeln(
          '    await initializeDartloom(scope: DartloomStartupScope.background);')
      ..writeln('    return DartloomSyncWorkerSession(')
      ..writeln('      run: () async {')
      ..writeln(
          '        final service = Dartloom.get<SyncService>(name: instanceName);')
      ..writeln('        return (await service.syncNow()).isSuccess;')
      ..writeln('      },')
      ..writeln('      dispose: disposeDartloom,')
      ..writeln('    );')
      ..writeln('  });')
      ..writeln('}')
      ..writeln();
  }
  buffer
    ..writeln(
        'String get _dartloomCurrentPlatform => kIsWeb ? \'web\' : switch (defaultTargetPlatform) {')
    ..writeln("  TargetPlatform.android => 'android',")
    ..writeln("  TargetPlatform.iOS => 'ios',")
    ..writeln("  TargetPlatform.linux => 'linux',")
    ..writeln("  TargetPlatform.macOS => 'macos',")
    ..writeln("  TargetPlatform.windows => 'windows',")
    ..writeln("  TargetPlatform.fuchsia => 'fuchsia',")
    ..writeln('};')
    ..writeln()
    ..writeln('bool _dartloomSupportsCurrentPlatform(Set<String> platforms) {')
    ..writeln('  return platforms.contains(_dartloomCurrentPlatform);')
    ..writeln('}')
    ..writeln();
  if (_requiresEnvironment(config)) {
    buffer
      ..writeln('String _requiredEnvironment(String name) {')
      ..writeln('  final value = String.fromEnvironment(name);')
      ..writeln('  if (value.isEmpty) {')
      ..writeln(
          "    throw DartloomException('required --dart-define=\$name=... is missing.');")
      ..writeln('  }')
      ..writeln('  return value;')
      ..writeln('}')
      ..writeln();
  }
  if (enabled.contains(Capability.resident)) {
    buffer
      ..writeln(
          'ResidentConfiguration _dartloomResidentConfiguration(Map<String, Object?> options) {')
      ..writeln("  final rawMenu = options['menu'];")
      ..writeln('  final menu = rawMenu is List')
      ..writeln('      ? rawMenu.map((entry) {')
      ..writeln('          if (entry is! Map) {')
      ..writeln(
          "            throw DartloomException('resident menu entries must be maps.');")
      ..writeln('          }')
      ..writeln("          if (entry['separator'] == true) {")
      ..writeln('            return const ResidentMenuItem.separator();')
      ..writeln('          }')
      ..writeln("          final id = entry['id'];")
      ..writeln("          final label = entry['label'];")
      ..writeln('          if (id is! String || label is! String) {')
      ..writeln(
          "            throw DartloomException('resident menu items require string id and label.');")
      ..writeln('          }')
      ..writeln('          return ResidentMenuItem.action(')
      ..writeln('            id: id, label: label,')
      ..writeln("            enabled: entry['enabled'] != false,")
      ..writeln('          );')
      ..writeln('        }).toList(growable: false)')
      ..writeln('      : const <ResidentMenuItem>[];')
      ..writeln('  return ResidentConfiguration(')
      ..writeln('    menu: menu,')
      ..writeln(
          "    leftClick: _dartloomResidentClickAction(options['left_click']),")
      ..writeln(
          "    rightClick: _dartloomResidentClickAction(options['right_click'], fallback: ResidentClickAction.showMenu),")
      ..writeln(
          "    exitMenuItemId: options['exit_menu_item_id'] as String? ?? 'quit',")
      ..writeln('  );')
      ..writeln('}')
      ..writeln()
      ..writeln(
          'ResidentClickAction _dartloomResidentClickAction(Object? value, {')
      ..writeln('  ResidentClickAction fallback = ResidentClickAction.restore,')
      ..writeln('}) => switch (value) {')
      ..writeln("      'menu' => ResidentClickAction.showMenu,")
      ..writeln("      'ignore' => ResidentClickAction.ignore,")
      ..writeln("      'restore' => ResidentClickAction.restore,")
      ..writeln('      _ => fallback,')
      ..writeln('    };')
      ..writeln();
  }
  if (enabled.contains(Capability.localization)) {
    buffer
      ..writeln(
          'final _dartloomFallbackLocalization = GenL10nLocalizationService(')
      ..writeln('  supportedLocales: AppLocalizations.supportedLocales,')
      ..writeln('  applicationDelegate: AppLocalizations.delegate,')
      ..writeln(');')
      ..writeln('List<Locale> get dartloomSupportedLocales =>')
      ..writeln('    Dartloom.contains<LocalizationService>()')
      ..writeln(
          '        ? Dartloom.get<LocalizationService>().supportedLocales')
      ..writeln('        : _dartloomFallbackLocalization.supportedLocales;')
      ..writeln(
          'List<LocalizationsDelegate<dynamic>> get dartloomLocalizationsDelegates =>')
      ..writeln('    Dartloom.contains<LocalizationService>()')
      ..writeln(
          '        ? Dartloom.get<LocalizationService>().localizationsDelegates')
      ..writeln(
          '        : _dartloomFallbackLocalization.localizationsDelegates;');
  } else {
    buffer
      ..writeln("const dartloomSupportedLocales = <Locale>[Locale('en')];")
      ..writeln('const dartloomLocalizationsDelegates =')
      ..writeln('    <LocalizationsDelegate<dynamic>>[];');
  }
  return buffer.toString();
}

void _writeOfficialFactories(StringBuffer buffer, DartloomConfig config) {
  final instances = config.capabilities;
  if (_uses(instances, Capability.settings, 'shared_preferences')) {
    buffer.writeln(
      "    'shared_preferences': (_) => DartloomBinding<SettingsStore>(SharedPreferencesSettingsStore()),",
    );
  }
  if (_uses(instances, Capability.settings, 'secure_storage')) {
    buffer.writeln(
      "    'secure_storage': (_) => const DartloomBinding<SettingsStore>(SecureSettingsStore()),",
    );
  }
  if (_uses(instances, Capability.storage, 'text_file')) {
    buffer
      ..writeln("    'text_file': (context) async {")
      ..writeln(
          "      final value = await TextFileStore.open(path: context.options['path'] as String? ?? 'dartloom/text');")
      ..writeln('      return DartloomBinding<TextStore>(value);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.storage, 'json_file')) {
    buffer
      ..writeln("    'json_file': (context) async {")
      ..writeln(
          "      final value = await JsonFileStore.open(path: context.options['path'] as String? ?? 'dartloom/data.json');")
      ..writeln('      return DartloomBinding<JsonStore>(value);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.storage, 'json_directory')) {
    buffer
      ..writeln("    'json_directory': (context) async {")
      ..writeln('      final value = await JsonDirectoryStore.open(')
      ..writeln(
          "        path: context.options['path'] as String? ?? 'Dartloom',")
      ..writeln(
          "        metadataPath: context.options['metadata_path'] as String?,")
      ..writeln(
          "        hierarchical: context.options['hierarchical'] as bool? ?? false,")
      ..writeln(
          "        legacyJsonPath: context.options['legacy_json_path'] as String?,")
      ..writeln(
          "        legacyKeyPrefix: context.options['legacy_key_prefix'] as String? ?? '',")
      ..writeln(
          "        allowedKeys: ((context.options['allowed_keys'] as List?) ?? const []).cast<String>().toSet(),")
      ..writeln(
          "        allowedPrefixes: ((context.options['allowed_prefixes'] as List?) ?? const []).cast<String>(),")
      ..writeln(
          "        seed: ((context.options['seed'] as Map?) ?? const {}).cast<String, Object?>(),")
      ..writeln('      );')
      ..writeln(
          '      return DartloomBinding<JsonStore>(value, dispose: value.close);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.storage, 'drift')) {
    buffer
      ..writeln("    'drift': (context) async {")
      ..writeln(
          "      final value = DriftDocumentStore.open(name: context.options['name'] as String? ?? 'dartloom');")
      ..writeln('      await value.initialize();')
      ..writeln(
          '      return DartloomBinding<DatabaseStore>(value, dispose: value.close);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.logging, 'logger')) {
    buffer.writeln(
      "    'logger': (_) => DartloomBinding<AppLogger>(LoggerAppLogger()),",
    );
  }
  if (_uses(instances, Capability.autostart, 'launch_at_startup')) {
    buffer
      ..writeln(
          "    'launch_at_startup': (context) => DartloomBinding<AutostartService>(")
      ..writeln('      LaunchAtStartupService(')
      ..writeln(
          "        appName: context.options['app_name'] as String? ?? ${_dart(config.app.name)},")
      ..writeln(
          "        appPath: context.options['app_path'] as String? ?? Platform.resolvedExecutable,")
      ..writeln(
          "        packageName: context.options['package_name'] as String? ?? ${_dart('${config.app.organization}.${config.app.name}')},")
      ..writeln('      ),')
      ..writeln('    ),');
  }
  if (_uses(instances, Capability.localization, 'gen_l10n')) {
    buffer
      ..writeln("    'gen_l10n': (_) => DartloomBinding<LocalizationService>(")
      ..writeln('      GenL10nLocalizationService(')
      ..writeln('        supportedLocales: AppLocalizations.supportedLocales,')
      ..writeln('        applicationDelegate: AppLocalizations.delegate,')
      ..writeln('      ),')
      ..writeln('    ),');
  }
  if (_uses(instances, Capability.resident, 'tray')) {
    buffer
      ..writeln("    'tray': (context) async {")
      ..writeln('      final value = TrayResidentService(')
      ..writeln(
          "        tooltip: context.options['tooltip'] as String? ?? 'Dartloom application',")
      ..writeln(
          "        linuxIconPath: context.options['icon_path_linux'] as String?,")
      ..writeln(
          "        macosIconPath: context.options['icon_path_macos'] as String?,")
      ..writeln(
          "        windowsIconPath: context.options['icon_path_windows'] as String?,")
      ..writeln('      );')
      ..writeln(
          "      await value.initialize(iconPath: context.options['icon_path'] as String, configuration: _dartloomResidentConfiguration(context.options));")
      ..writeln(
          '      return DartloomBinding<ResidentService>(value, dispose: value.dispose);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.messaging, 'memory_messaging')) {
    buffer
      ..writeln("    'memory_messaging': (_) {")
      ..writeln('      final value = MemoryMessagingConnection();')
      ..writeln('      return DartloomBinding<MessagingConnection>(')
      ..writeln('        value, dispose: value.close,')
      ..writeln('      );')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.pairing, 'memory_pairing')) {
    buffer
      ..writeln("    'memory_pairing': (_) {")
      ..writeln('      final value = MemoryPairingCapability();')
      ..writeln('      return DartloomBinding<PairingCapability>(')
      ..writeln('        value, dispose: value.close,')
      ..writeln('      );')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.singleton, 'socket')) {
    buffer
      ..writeln("    'socket': (context) {")
      ..writeln(
          "      final value = SocketSingleInstanceService(residentProvider: () => context.maybeGet<ResidentService>());")
      ..writeln('      return DartloomBinding<SingleInstanceService>(value);')
      ..writeln('    },');
  }
  if (instances.containsKey(Capability.sync)) {
    buffer
      ..writeln("    'sync_profile_scope': (context) async {")
      ..writeln('      final value = await SyncProfileScope.open(')
      ..writeln("        context.get<SettingsStore>(), context.name,")
      ..writeln('      );')
      ..writeln(
          '      return DartloomBinding<SyncProfileScope>(value, dispose: value.dispose);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.sync, 'etag')) {
    buffer
      ..writeln("    'etag': (context) async {")
      ..writeln(
          "      final replicaName = (context.options['replica'] as String).substring('storage.'.length);")
      ..writeln(
          '      final localStore = context.get<ReplicaStore>(name: replicaName);')
      ..writeln(
          '      final profileScope = context.get<SyncProfileScope>(name: context.name);')
      ..writeln('      final profiles = SettingsSyncProfileRepository(')
      ..writeln('        instanceName: context.name,')
      ..writeln('        metadata: context.get<SettingsStore>(),')
      ..writeln(
          "        secretsStore: context.get<SettingsStore>(name: 'sync_secrets'),")
      ..writeln('        scope: profileScope,')
      ..writeln('      );')
      ..writeln('      final state = SettingsReconciliationStateRepository(')
      ..writeln(
          '        context.get<SettingsStore>(), instanceName: context.name,')
      ..writeln('      );')
      ..writeln('      final backend = WebDavBackendFactory(')
      ..writeln(
          "        defaultRootPath: context.options['backend_root_path'] as String? ?? 'Dartloom',")
      ..writeln(
          "        connectTimeout: SyncPolicyCodec.parseDuration(context.options['backend_connect_timeout'] as String),")
      ..writeln(
          "        requestTimeout: SyncPolicyCodec.parseDuration(context.options['backend_request_timeout'] as String),")
      ..writeln(
          "        maxParallelRequests: context.options['backend_max_parallel_requests'] as int,")
      ..writeln(
          "        createMissingCollections: context.options['backend_create_missing_collections'] as bool,")
      ..writeln(
          "        hierarchical: context.options['backend_hierarchical'] as bool? ?? false,")
      ..writeln(
          "        probeDepthInfinity: context.options['backend_probe_depth_infinity'] as bool? ?? false,")
      ..writeln(
          "        legacyCollection: context.options['backend_legacy_collection'] as String?,")
      ..writeln(
          "        legacyKeyPrefix: context.options['backend_legacy_key_prefix'] as String? ?? '',")
      ..writeln(
          "        listingLimitHint: context.options['backend_listing_limit_hint'] as int? ?? 750,")
      ..writeln('      );')
      ..writeln('      SyncMergePolicy? merge;')
      ..writeln(
          "      final mergeFactory = context.options['merge_factory'] as String?;")
      ..writeln('      if (mergeFactory != null) {')
      ..writeln(
        '        final factory = factories[mergeFactory];',
      )
      ..writeln('        if (factory == null) {')
      ..writeln(
        "          throw DartloomException('missing merge factory \$mergeFactory.');",
      )
      ..writeln('        }')
      ..writeln('        final binding = await factory(context);')
      ..writeln('        if (binding.value is! SyncMergePolicy) {')
      ..writeln(
          "          throw DartloomException('merge factory \$mergeFactory must return SyncMergePolicy.');")
      ..writeln('        }')
      ..writeln('        merge = binding.value as SyncMergePolicy;')
      ..writeln('      }')
      ..writeln('      FlutterSyncRuntimeSignals? runtime;')
      ..writeln('      if (scope != DartloomStartupScope.background) {')
      ..writeln('        runtime = FlutterSyncRuntimeSignals();')
      ..writeln('        await runtime.start();')
      ..writeln('      }')
      ..writeln('      final coordinator = SyncCoordinator(')
      ..writeln('        instanceName: context.name,')
      ..writeln(
          "        policy: SyncPolicyCodec.resolve((context.options['policy'] as Map).cast<String, Object?>(), _dartloomCurrentPlatform),")
      ..writeln('        profiles: profiles,')
      ..writeln(
          '        localFactory: ReplicaStoreLocalReplicaFactory(localStore),')
      ..writeln('        stateRepository: state,')
      ..writeln('        reconciler: const EtagReconciler(),')
      ..writeln("        backends: {'webdav': backend},")
      ..writeln('        runtimeSignals: runtime,')
      ..writeln(
          '        backgroundScheduler: scope == DartloomStartupScope.background ? null : WorkmanagerSyncBackgroundScheduler(callbackDispatcher: dartloomSyncCallbackDispatcher),')
      ..writeln('        merge: merge,')
      ..writeln('      );')
      ..writeln('      await coordinator.start();')
      ..writeln('      return DartloomBinding<SyncService>(')
      ..writeln('        coordinator,')
      ..writeln('        dispose: () async {')
      ..writeln('          await coordinator.dispose();')
      ..writeln('          await runtime?.dispose();')
      ..writeln('        },')
      ..writeln('      );')
      ..writeln('    },');
  }
}

void _writeRegistrations(StringBuffer buffer, DartloomConfig config) {
  final syncInstances = config.capabilities[Capability.sync] ?? const {};
  for (final capability in [
    if (config.capabilities.containsKey(Capability.singleton))
      Capability.singleton,
    ...Capability.values.where(
      (capability) => capability != Capability.singleton,
    ),
  ]) {
    final instances = config.capabilities[capability] ?? const {};
    for (final entry in instances.entries) {
      final instance = entry.value;
      final type = _serviceType(capability, entry.key, instance);
      final factory = instance.factory ?? instance.implementation;
      final platforms = _supportedPlatforms(capability, instance);
      final options = <String, Object?>{...instance.options};
      if (capability == Capability.sync) {
        options['replica'] = instance.replica;
        options['policy'] = instance.policy;
        for (final option in instance.backend?.options.entries ??
            const <MapEntry<String, Object?>>[]) {
          options['backend_${option.key}'] = option.value;
        }
        if (instance.mergeFactory != null) {
          options['merge_factory'] = instance.mergeFactory;
        }
      }
      buffer
        ..writeln(
          "      if (_dartloomSupportsCurrentPlatform(const {${platforms.map((platform) => _dart(platform.name)).join(', ')}}))",
        )
        ..writeln('      DartloomRegistration<$type>(')
        ..writeln("        capability: '${capability.name}',")
        ..writeln('        name: ${_dart(entry.key)},')
        ..writeln('        factory: ${_dart(factory)},')
        ..writeln(
          '        scope: DartloomStartupScope.${capability == Capability.settings || capability == Capability.storage || capability == Capability.sync ? 'both' : 'foreground'},',
        )
        ..writeln('        options: ${_dartMap(options)},');
      final dependencies = <String>{
        ...instance.dependsOn,
        if (capability == Capability.sync && instance.replica != null)
          instance.replica!,
        if (capability == Capability.sync) 'sync_profile.${entry.key}',
        if (capability == Capability.sync) 'settings.default',
        if (capability == Capability.sync) 'settings.sync_secrets',
      };
      if (dependencies.isNotEmpty) {
        buffer
          ..writeln('        dependsOn: const [')
          ..writeAll(
            dependencies.map((value) {
              final parts = value.split('.');
              return "          DartloomReference('${parts.first}', '${parts.last}'),\n";
            }),
          )
          ..writeln('        ],');
      }
      buffer.writeln('      ),');
    }
  }
  for (final entry in syncInstances.entries) {
    final platforms = _supportedPlatforms(Capability.sync, entry.value);
    buffer
      ..writeln(
        "      if (_dartloomSupportsCurrentPlatform(const {${platforms.map((platform) => _dart(platform.name)).join(', ')}}))",
      )
      ..writeln('      DartloomRegistration<SyncProfileScope>(')
      ..writeln("        capability: 'sync_profile',")
      ..writeln('        name: ${_dart(entry.key)},')
      ..writeln("        factory: 'sync_profile_scope',")
      ..writeln('        scope: DartloomStartupScope.both,')
      ..writeln('        dependsOn: const [')
      ..writeln("          DartloomReference('settings', 'default'),")
      ..writeln('        ],')
      ..writeln('      ),');
  }
}

Set<TargetPlatform> _supportedPlatforms(
  Capability capability,
  CapabilityInstanceConfig instance,
) {
  final adapter = CapabilityRegistry.implementation(
    capability,
    instance.implementation,
  );
  final supported =
      adapter?.platforms ?? CapabilityRegistry.all[capability]!.platforms;
  final configured = instance.platforms;
  return configured == null ? supported : supported.intersection(configured);
}

String _serviceType(
  Capability capability,
  String name,
  CapabilityInstanceConfig instance,
) =>
    switch (capability) {
      Capability.settings => 'SettingsStore',
      Capability.storage when instance.implementation == 'app_file_replica' =>
        'ReplicaStore',
      Capability.storage => switch (name) {
          'text' => 'TextStore',
          'json' => 'JsonStore',
          'database' => 'DatabaseStore',
          _ => 'Object',
        },
      Capability.logging => 'AppLogger',
      Capability.autostart => 'AutostartService',
      Capability.sync => 'SyncService',
      Capability.localization => 'LocalizationService',
      Capability.resident => 'ResidentService',
      Capability.messaging => 'MessagingConnection',
      Capability.pairing => 'PairingCapability',
      Capability.singleton => 'SingleInstanceService',
    };

bool _uses(
  Map<Capability, Map<String, CapabilityInstanceConfig>> capabilities,
  Capability capability,
  String implementation,
) =>
    capabilities[capability]
        ?.values
        .any((instance) => instance.implementation == implementation) ??
    false;

bool _requiresEnvironment(DartloomConfig config) {
  bool contains(Object? value) {
    if (value is String) {
      return RegExp(r'^\$\{[A-Z][A-Z0-9_]*\}$').hasMatch(value);
    }
    if (value is Iterable) {
      return value.any(contains);
    }
    if (value is Map) {
      return value.values.any(contains);
    }
    return false;
  }

  for (final capability in config.capabilities.values) {
    for (final instance in capability.values) {
      if (contains(instance.options) || contains(instance.backend?.options)) {
        return true;
      }
    }
  }
  return false;
}

String _dart(Object? value) {
  if (value is String) {
    final environment = RegExp(r'^\$\{([A-Z][A-Z0-9_]*)\}$').firstMatch(value);
    if (environment != null) {
      return "_requiredEnvironment('${environment.group(1)}')";
    }
    return jsonEncode(value);
  }
  if (value == null || value is bool || value is num) return '$value';
  if (value is List) return '[${value.map(_dart).join(', ')}]';
  if (value is Map<String, Object?>) return _dartMap(value);
  throw ArgumentError('Unsupported generated option: $value');
}

String _dartMap(Map<String, Object?> value) =>
    '<String, Object?>{${value.entries.map((entry) => '${jsonEncode(entry.key)}: ${_dart(entry.value)}').join(', ')}}';

String appShell(DartloomConfig config) =>
    '''import 'package:flutter/material.dart';

import '../capabilities/capabilities.dart';

class DartloomApp extends StatelessWidget {
  const DartloomApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        title: ${jsonEncode(config.app.name)},
        localizationsDelegates: dartloomLocalizationsDelegates,
        supportedLocales: dartloomSupportedLocales,
        home: const Scaffold(body: Center(child: Text('Dartloom app'))),
      );
}
''';

const capabilityBootstrap =
    '''import 'package:dartloom_runtime/dartloom_runtime.dart';
import 'package:flutter/widgets.dart';

import 'capabilities.dart';

/// Dartloom-owned startup fragment. Call this from the application's main
/// method before creating its widget tree.
Future<void> bootstrapDartloom({
  Map<String, DartloomFactory> customFactories = const {},
}) async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDartloom(customFactories: customFactories);
}
''';

const appOwnedReplicaFactory = '''import 'dart:io';

import 'package:dartloom_runtime/dartloom_runtime.dart';
import 'package:dartloom_storage/dartloom_storage.dart';
import 'package:dartloom_storage_json_file/dartloom_storage_json_file.dart';

/// Application-owned paths for the synchronized JSON replica.
///
/// Resolve both absolute directories through the same application path API
/// used by the rest of the app. Metadata must remain outside the business root.
Future<DartloomBinding<Object>> createJsonReplicaStore(
  DartloomFactoryContext context,
) async {
  final (businessRoot, metadataRoot) = await resolveJsonReplicaDirectories();
  final value = await JsonDirectoryStore.openAt(
    directory: businessRoot,
    metadataDirectory: metadataRoot,
  );
  return DartloomBinding<ReplicaStore>(value, dispose: value.close);
}

Future<(Directory, Directory)> resolveJsonReplicaDirectories() {
  // TODO(app): use the application's path service to return absolute business
  // and metadata directories. Do not put metadata inside the business root.
  throw const DartloomException(
    'Implement application-owned JSON replica path resolution.',
  );
}

final dartloomApplicationFactories = <String, DartloomFactory>{
  'createJsonReplicaStore': createJsonReplicaStore,
};
''';

String agentInstructions(DartloomConfig config) {
  final projectPlatforms = _platformList(config.platforms);
  final rows = <String>[];
  for (final capability in Capability.values) {
    final instances = config.capabilities[capability] ?? const {};
    for (final entry in instances.entries) {
      final instance = entry.value;
      final effectivePlatforms = _supportedPlatforms(
        capability,
        instance,
      ).intersection(config.platforms);
      rows.add(
        '| `${capability.name}.${entry.key}` | '
        '`${CapabilityRegistry.all[capability]!.contractPackage}` | '
        '`${instance.implementation}` | ${_platformList(effectivePlatforms)} |',
      );
    }
  }
  final capabilityRows =
      rows.isEmpty ? '| None | - | - | - |' : rows.join('\n');
  final syncRows = <String>[];
  for (final entry in config.capabilities[Capability.sync]?.entries ??
      const <MapEntry<String, CapabilityInstanceConfig>>[]) {
    final configured =
        deepMerge(SyncOptionSchemas.policy.defaults(), entry.value.policy);
    final base = Map<String, Object?>.fromEntries(
      configured.entries.where((item) => item.key != 'platforms'),
    );
    final overrides = configured['platforms'] is Map
        ? (configured['platforms'] as Map).cast<String, Object?>()
        : const <String, Object?>{};
    for (final platform in config.platforms) {
      final override = overrides[platform.name] is Map
          ? (overrides[platform.name] as Map).cast<String, Object?>()
          : const <String, Object?>{};
      final resolved = deepMerge(
          base,
          Map.fromEntries(
              override.entries.where((item) => item.key != 'background')));
      final background = override['background'] is Map &&
          (override['background'] as Map)['enabled'] == true;
      syncRows.add(
        '| `sync.${entry.key}` | ${platform.name} | '
        '${readPath(resolved, 'mode')} | '
        '${readPath(resolved, 'discovery.remote_changes')} | '
        '${readPath(resolved, 'discovery.poll_interval')} | '
        '${background ? 'enabled' : 'disabled'} |',
      );
    }
  }
  final syncPolicyTable = syncRows.isEmpty
      ? ''
      : '''

## Sync policy by platform

Startup, resume, local-write, connectivity, polling, retry, conflict, and
background behavior is owned by Dartloom. Feature code calls `SyncService`
and must not reproduce these triggers.

| Sync instance | Platform | Mode | Remote discovery | Poll interval | System background |
| --- | --- | --- | --- | --- | --- |
${syncRows.join('\n')}
''';

  return '''# Agent Instructions

This project is managed by Dartloom.

Dartloom repository: https://github.com/wkzMagician/dartloom

## Dartloom commands

Install or refresh the CLI:

```bash
dart install --overwrite https://github.com/wkzMagician/dartloom.git --git-path cli/dartloom_cli
```

Upgrade Dartloom-managed project files and dependencies:

```bash
dartloom project upgrade
```

Check the project and build a Windows release package:

```bash
dartloom check
dartloom package windows exe
```

1. Read `dartloom.yaml` before changing infrastructure.
2. Feature code depends on capability contracts and obtains implementations with
   `Dartloom.get<T>(name: ...)`; do not import adapter packages in feature code.
3. Register app-owned implementations by passing their factory map to
   `bootstrapDartloom(customFactories: ...)`. Keep factory implementations in
   application-owned files; do not add them to generated capability files.
4. Business code belongs in `lib/features`; shared app glue belongs in `lib/app`.
5. Dartloom owns `lib/capabilities/capabilities.dart` and
   `lib/capabilities/bootstrap.dart`. Application files, including `lib/app`
   and ARB translations, are never overwritten by `dartloom project upgrade`.

## Capability platform support

Enabled project targets: $projectPlatforms.

Generated registration is platform-aware. Treat a capability as optional when
the current target is not listed below, and use `Dartloom.maybeGet<T>()` for
optional feature UI instead of duplicating operating-system checks.

| Capability instance | Contract package | Implementation | Project targets |
| --- | --- | --- | --- |
$capabilityRows
$syncPolicyTable

Before finishing, run `dart format .`, `flutter analyze`, and `flutter test`.
''';
}

String _platformList(Set<TargetPlatform> platforms) {
  final names = TargetPlatform.values
      .where(platforms.contains)
      .map((platform) => platform.name)
      .join(', ');
  return names.isEmpty ? 'none' : names;
}

const ciWorkflow = '''name: CI
on: [push, pull_request]
jobs:
  check:
    uses: wkzMagician/dartloom/.github/workflows/flutter_ci.yml@main
''';

String releaseWorkflow(DartloomConfig config) => '''name: Release
on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:
jobs:
  release:
    uses: wkzMagician/dartloom/.github/workflows/flutter_release.yml@main
    permissions:
      contents: write
    with:
      build_android: ${config.platforms.contains(TargetPlatform.android)}
      build_windows: ${config.platforms.contains(TargetPlatform.windows)}
      build_linux: ${config.platforms.contains(TargetPlatform.linux)}
''';

const l10nYaml = '''arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
''';

const appEnArb = '''{
  "@@locale": "en",
  "appTitle": "Dartloom app"
}
''';

const appZhArb = '''{
  "@@locale": "zh",
  "appTitle": "Dartloom 应用"
}
''';
