import 'dart:convert';

import '../capabilities/capability_registry.dart';
import '../config/dartloom_config.dart';

String capabilityGlue(DartloomConfig config) {
  final enabled = config.enabledCapabilities;
  final imports = <String>{
    "import 'package:dartloom_runtime/dartloom_runtime.dart';",
    "import 'package:flutter/foundation.dart';",
    "import 'package:flutter/widgets.dart';",
  };
  if (enabled.contains(Capability.settings)) {
    imports.add("import 'package:dartloom_settings/dartloom_settings.dart';");
  }
  if (enabled.contains(Capability.storage)) {
    imports.add("import 'package:dartloom_storage/dartloom_storage.dart';");
  }
  if (enabled.contains(Capability.logging)) {
    imports.add("import 'package:dartloom_logging/dartloom_logging.dart';");
  }
  if (enabled.contains(Capability.autostart)) {
    imports
      ..add("import 'dart:io';")
      ..add("import 'package:dartloom_autostart/dartloom_autostart.dart';");
  }
  if (enabled.contains(Capability.sync)) {
    imports.add("import 'package:dartloom_sync/dartloom_sync.dart';");
  }
  if (enabled.contains(Capability.localization)) {
    imports
      ..add(
        "import 'package:dartloom_localization/dartloom_localization.dart';",
      )
      ..add(
        "import 'package:${config.app.name}/l10n/app_localizations.dart';",
      );
  }
  if (enabled.contains(Capability.resident)) {
    imports.add("import 'package:dartloom_resident/dartloom_resident.dart';");
  }
  for (final capability in config.capabilities.entries) {
    for (final instance in capability.value.values) {
      final metadata = CapabilityRegistry.implementation(
        capability.key,
        instance.implementation,
      );
      if (metadata != null) {
        imports.add(
          "import 'package:${metadata.packageName}/${metadata.packageName}.dart';",
        );
      }
      if (capability.key == Capability.sync &&
          instance.backend?.implementation == 'webdav') {
        imports.add(
          "import 'package:dartloom_sync_webdav/dartloom_sync_webdav.dart';",
        );
      }
    }
  }

  final buffer = StringBuffer()
    ..writeln(
        '// Generated by Dartloom. This file is overwritten by project update.')
    ..writeln(imports.join('\n'))
    ..writeln()
    ..writeln('Future<void> initializeDartloom({')
    ..writeln('  Map<String, DartloomFactory> customFactories = const {},')
    ..writeln('}) async {')
    ..writeln('  late final Map<String, DartloomFactory> factories;')
    ..writeln('  final officialFactories = <String, DartloomFactory>{');
  _writeOfficialFactories(buffer, config);
  buffer
    ..writeln('  };')
    ..writeln('  final collisions = officialFactories.keys.toSet()')
    ..writeln('      .intersection(customFactories.keys.toSet());')
    ..writeln('  if (collisions.isNotEmpty) {')
    ..writeln(
        "    throw DartloomException('custom factories cannot replace official factories: \$collisions');")
    ..writeln('  }')
    ..writeln('  factories = {...officialFactories, ...customFactories};')
    ..writeln('  await Dartloom.initialize(')
    ..writeln('    <DartloomRegistration<Object>>[');
  _writeRegistrations(buffer, config);
  buffer
    ..writeln('    ],')
    ..writeln('    factories: factories,')
    ..writeln('  );')
    ..writeln('}')
    ..writeln()
    ..writeln('Future<void> disposeDartloom() => Dartloom.dispose();')
    ..writeln();
  buffer
    ..writeln('bool _dartloomSupportsCurrentPlatform(Set<String> platforms) {')
    ..writeln(
        "  final current = kIsWeb ? 'web' : switch (defaultTargetPlatform) {")
    ..writeln("    TargetPlatform.android => 'android',")
    ..writeln("    TargetPlatform.iOS => 'ios',")
    ..writeln("    TargetPlatform.linux => 'linux',")
    ..writeln("    TargetPlatform.macOS => 'macos',")
    ..writeln("    TargetPlatform.windows => 'windows',")
    ..writeln("    TargetPlatform.fuchsia => 'fuchsia',")
    ..writeln('  };')
    ..writeln('  return platforms.contains(current);')
    ..writeln('}')
    ..writeln();
  if (_requiresEnvironment(config)) {
    buffer
      ..writeln('String _requiredEnvironment(String name) {')
      ..writeln('  final value = String.fromEnvironment(name);')
      ..writeln('  if (value.isEmpty) {')
      ..writeln(
          "    throw DartloomException('required --dart-define=\$name=... is missing.');")
      ..writeln('  }')
      ..writeln('  return value;')
      ..writeln('}')
      ..writeln();
  }
  if (enabled.contains(Capability.resident)) {
    buffer
      ..writeln(
          'ResidentConfiguration _dartloomResidentConfiguration(Map<String, Object?> options) {')
      ..writeln("  final rawMenu = options['menu'];")
      ..writeln('  final menu = rawMenu is List')
      ..writeln('      ? rawMenu.map((entry) {')
      ..writeln('          if (entry is! Map) {')
      ..writeln(
          "            throw DartloomException('resident menu entries must be maps.');")
      ..writeln('          }')
      ..writeln("          if (entry['separator'] == true) {")
      ..writeln('            return const ResidentMenuItem.separator();')
      ..writeln('          }')
      ..writeln("          final id = entry['id'];")
      ..writeln("          final label = entry['label'];")
      ..writeln('          if (id is! String || label is! String) {')
      ..writeln(
          "            throw DartloomException('resident menu items require string id and label.');")
      ..writeln('          }')
      ..writeln('          return ResidentMenuItem.action(')
      ..writeln('            id: id, label: label,')
      ..writeln("            enabled: entry['enabled'] != false,")
      ..writeln('          );')
      ..writeln('        }).toList(growable: false)')
      ..writeln('      : const <ResidentMenuItem>[];')
      ..writeln('  return ResidentConfiguration(')
      ..writeln('    menu: menu,')
      ..writeln(
          "    leftClick: _dartloomResidentClickAction(options['left_click']),")
      ..writeln(
          "    rightClick: _dartloomResidentClickAction(options['right_click'], fallback: ResidentClickAction.showMenu),")
      ..writeln(
          "    exitMenuItemId: options['exit_menu_item_id'] as String? ?? 'quit',")
      ..writeln('  );')
      ..writeln('}')
      ..writeln()
      ..writeln(
          'ResidentClickAction _dartloomResidentClickAction(Object? value, {')
      ..writeln('  ResidentClickAction fallback = ResidentClickAction.restore,')
      ..writeln('}) => switch (value) {')
      ..writeln("      'menu' => ResidentClickAction.showMenu,")
      ..writeln("      'ignore' => ResidentClickAction.ignore,")
      ..writeln("      'restore' => ResidentClickAction.restore,")
      ..writeln('      _ => fallback,')
      ..writeln('    };')
      ..writeln();
  }
  if (enabled.contains(Capability.localization)) {
    buffer
      ..writeln(
          'final _dartloomFallbackLocalization = GenL10nLocalizationService(')
      ..writeln('  supportedLocales: AppLocalizations.supportedLocales,')
      ..writeln('  applicationDelegate: AppLocalizations.delegate,')
      ..writeln(');')
      ..writeln('List<Locale> get dartloomSupportedLocales =>')
      ..writeln('    Dartloom.contains<LocalizationService>()')
      ..writeln(
          '        ? Dartloom.get<LocalizationService>().supportedLocales')
      ..writeln('        : _dartloomFallbackLocalization.supportedLocales;')
      ..writeln(
          'List<LocalizationsDelegate<dynamic>> get dartloomLocalizationsDelegates =>')
      ..writeln('    Dartloom.contains<LocalizationService>()')
      ..writeln(
          '        ? Dartloom.get<LocalizationService>().localizationsDelegates')
      ..writeln(
          '        : _dartloomFallbackLocalization.localizationsDelegates;');
  } else {
    buffer
      ..writeln("const dartloomSupportedLocales = <Locale>[Locale('en')];")
      ..writeln('const dartloomLocalizationsDelegates =')
      ..writeln('    <LocalizationsDelegate<dynamic>>[];');
  }
  return buffer.toString();
}

void _writeOfficialFactories(StringBuffer buffer, DartloomConfig config) {
  final instances = config.capabilities;
  if (_uses(instances, Capability.settings, 'shared_preferences')) {
    buffer.writeln(
      "    'shared_preferences': (_) => DartloomBinding<SettingsStore>(SharedPreferencesSettingsStore()),",
    );
  }
  if (_uses(instances, Capability.settings, 'secure_storage')) {
    buffer.writeln(
      "    'secure_storage': (_) => const DartloomBinding<SettingsStore>(SecureSettingsStore()),",
    );
  }
  if (_uses(instances, Capability.storage, 'text_file')) {
    buffer
      ..writeln("    'text_file': (context) async {")
      ..writeln(
          "      final value = await TextFileStore.open(path: context.options['path'] as String? ?? 'dartloom/text');")
      ..writeln('      return DartloomBinding<TextStore>(value);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.storage, 'json_file')) {
    buffer
      ..writeln("    'json_file': (context) async {")
      ..writeln(
          "      final value = await JsonFileStore.open(path: context.options['path'] as String? ?? 'dartloom/data.json');")
      ..writeln('      return DartloomBinding<JsonStore>(value);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.storage, 'drift')) {
    buffer
      ..writeln("    'drift': (context) async {")
      ..writeln(
          "      final value = DriftDocumentStore.open(name: context.options['name'] as String? ?? 'dartloom');")
      ..writeln('      await value.initialize();')
      ..writeln(
          '      return DartloomBinding<DatabaseStore>(value, dispose: value.close);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.logging, 'logger')) {
    buffer.writeln(
      "    'logger': (_) => DartloomBinding<AppLogger>(LoggerAppLogger()),",
    );
  }
  if (_uses(instances, Capability.autostart, 'launch_at_startup')) {
    buffer
      ..writeln(
          "    'launch_at_startup': (context) => DartloomBinding<AutostartService>(")
      ..writeln('      LaunchAtStartupService(')
      ..writeln(
          "        appName: context.options['app_name'] as String? ?? ${_dart(config.app.name)},")
      ..writeln(
          "        appPath: context.options['app_path'] as String? ?? Platform.resolvedExecutable,")
      ..writeln(
          "        packageName: context.options['package_name'] as String? ?? ${_dart('${config.app.organization}.${config.app.name}')},")
      ..writeln('      ),')
      ..writeln('    ),');
  }
  if (_uses(instances, Capability.localization, 'gen_l10n')) {
    buffer
      ..writeln("    'gen_l10n': (_) => DartloomBinding<LocalizationService>(")
      ..writeln('      GenL10nLocalizationService(')
      ..writeln('        supportedLocales: AppLocalizations.supportedLocales,')
      ..writeln('        applicationDelegate: AppLocalizations.delegate,')
      ..writeln('      ),')
      ..writeln('    ),');
  }
  if (_uses(instances, Capability.resident, 'tray')) {
    buffer
      ..writeln("    'tray': (context) async {")
      ..writeln('      final value = TrayResidentService(')
      ..writeln(
          "        tooltip: context.options['tooltip'] as String? ?? 'Dartloom application',")
      ..writeln(
          "        linuxIconPath: context.options['icon_path_linux'] as String?,")
      ..writeln(
          "        macosIconPath: context.options['icon_path_macos'] as String?,")
      ..writeln(
          "        windowsIconPath: context.options['icon_path_windows'] as String?,")
      ..writeln('      );')
      ..writeln(
          "      await value.initialize(iconPath: context.options['icon_path'] as String, configuration: _dartloomResidentConfiguration(context.options));")
      ..writeln(
          '      return DartloomBinding<ResidentService>(value, dispose: value.dispose);')
      ..writeln('    },');
  }
  if (_uses(instances, Capability.sync, 'etag_object')) {
    buffer
      ..writeln("    'etag_object': (context) async {")
      ..writeln('      final localStores = <String, LocalSyncStore>{};')
      ..writeln(
          "      for (final reference in (context.options['stores'] as List).cast<String>()) {")
      ..writeln("        final name = reference.substring('storage.'.length);")
      ..writeln("        if (name == 'text') {")
      ..writeln(
          "          localStores[name] = TextLocalSyncStore(context.get<TextStore>(name: name));")
      ..writeln('        }')
      ..writeln("        if (name == 'json') {")
      ..writeln(
          "          localStores[name] = JsonLocalSyncStore(context.get<JsonStore>(name: name));")
      ..writeln('        }')
      ..writeln("        if (name == 'database') {")
      ..writeln(
          "          localStores[name] = DatabaseLocalSyncStore(context.get<DatabaseStore>(name: name));")
      ..writeln('        }')
      ..writeln('      }')
      ..writeln("      final remote = WebDavObjectStore(")
      ..writeln(
          "        baseUrl: Uri.parse(context.options['backend_base_url'] as String),")
      ..writeln(
          "        rootPath: context.options['backend_root_path'] as String? ?? 'Dartloom',")
      ..writeln(
          "        username: context.options['backend_username'] as String? ?? '',")
      ..writeln(
          "        password: context.options['backend_password'] as String? ?? '',")
      ..writeln('      );')
      ..writeln('      SyncMergePolicy? merge;')
      ..writeln(
          "      final mergeFactory = context.options['merge_factory'] as String?;")
      ..writeln('      if (mergeFactory != null) {')
      ..writeln(
        '        final factory = factories[mergeFactory];',
      )
      ..writeln('        if (factory == null) {')
      ..writeln(
        "          throw DartloomException('missing merge factory \$mergeFactory.');",
      )
      ..writeln('        }')
      ..writeln('        final binding = await factory(context);')
      ..writeln('        if (binding.value is! SyncMergePolicy) {')
      ..writeln(
          "          throw DartloomException('merge factory \$mergeFactory must return SyncMergePolicy.');")
      ..writeln('        }')
      ..writeln('        merge = binding.value as SyncMergePolicy;')
      ..writeln('      }')
      ..writeln(
          "      final state = JsonSyncStateStore(context.get<JsonStore>(name: 'json'), key: '__dartloom_sync/\${context.name}');")
      ..writeln('      return DartloomBinding<SyncEngine>(EtagSyncEngine(')
      ..writeln('        local: CompositeLocalSyncStore(localStores),')
      ..writeln('        remote: remote, stateStore: state, merge: merge,')
      ..writeln('      ));')
      ..writeln('    },');
  }
}

void _writeRegistrations(StringBuffer buffer, DartloomConfig config) {
  for (final capability in Capability.values) {
    final instances = config.capabilities[capability] ?? const {};
    for (final entry in instances.entries) {
      final instance = entry.value;
      final type = _serviceType(capability, entry.key);
      final factory = instance.factory ?? instance.implementation;
      final platforms = _supportedPlatforms(capability, instance);
      final options = <String, Object?>{...instance.options};
      if (capability == Capability.sync) {
        options['stores'] = instance.stores;
        for (final option in instance.backend?.options.entries ??
            const <MapEntry<String, Object?>>[]) {
          options['backend_${option.key}'] = option.value;
        }
        if (instance.mergeFactory != null) {
          options['merge_factory'] = instance.mergeFactory;
        }
      }
      buffer
        ..writeln(
          "      if (_dartloomSupportsCurrentPlatform(const {${platforms.map((platform) => _dart(platform.name)).join(', ')}}))",
        )
        ..writeln('      DartloomRegistration<$type>(')
        ..writeln("        capability: '${capability.name}',")
        ..writeln('        name: ${_dart(entry.key)},')
        ..writeln('        factory: ${_dart(factory)},')
        ..writeln('        options: ${_dartMap(options)},');
      final dependencies = <String>{
        ...instance.dependsOn,
        if (capability == Capability.sync) ...instance.stores,
        if (capability == Capability.sync) 'storage.json',
      };
      if (dependencies.isNotEmpty) {
        buffer
          ..writeln('        dependsOn: const [')
          ..writeAll(
            dependencies.map((value) {
              final parts = value.split('.');
              return "          DartloomReference('${parts.first}', '${parts.last}'),\n";
            }),
          )
          ..writeln('        ],');
      }
      buffer.writeln('      ),');
    }
  }
}

Set<TargetPlatform> _supportedPlatforms(
  Capability capability,
  CapabilityInstanceConfig instance,
) {
  final adapter = CapabilityRegistry.implementation(
    capability,
    instance.implementation,
  );
  final supported =
      adapter?.platforms ?? CapabilityRegistry.all[capability]!.platforms;
  final configured = instance.platforms;
  return configured == null ? supported : supported.intersection(configured);
}

String _serviceType(Capability capability, String name) => switch (capability) {
      Capability.settings => 'SettingsStore',
      Capability.storage => switch (name) {
          'text' => 'TextStore',
          'json' => 'JsonStore',
          'database' => 'DatabaseStore',
          _ => 'Object',
        },
      Capability.logging => 'AppLogger',
      Capability.autostart => 'AutostartService',
      Capability.sync => 'SyncEngine',
      Capability.localization => 'LocalizationService',
      Capability.resident => 'ResidentService',
    };

bool _uses(
  Map<Capability, Map<String, CapabilityInstanceConfig>> capabilities,
  Capability capability,
  String implementation,
) =>
    capabilities[capability]
        ?.values
        .any((instance) => instance.implementation == implementation) ??
    false;

bool _requiresEnvironment(DartloomConfig config) {
  bool contains(Object? value) {
    if (value is String) {
      return RegExp(r'^\$\{[A-Z][A-Z0-9_]*\}$').hasMatch(value);
    }
    if (value is Iterable) {
      return value.any(contains);
    }
    if (value is Map) {
      return value.values.any(contains);
    }
    return false;
  }

  for (final capability in config.capabilities.values) {
    for (final instance in capability.values) {
      if (contains(instance.options) || contains(instance.backend?.options)) {
        return true;
      }
    }
  }
  return false;
}

String _dart(Object? value) {
  if (value is String) {
    final environment = RegExp(r'^\$\{([A-Z][A-Z0-9_]*)\}$').firstMatch(value);
    if (environment != null) {
      return "_requiredEnvironment('${environment.group(1)}')";
    }
    return jsonEncode(value);
  }
  if (value == null || value is bool || value is num) return '$value';
  if (value is List) return '[${value.map(_dart).join(', ')}]';
  if (value is Map<String, Object?>) return _dartMap(value);
  throw ArgumentError('Unsupported generated option: $value');
}

String _dartMap(Map<String, Object?> value) =>
    '<String, Object?>{${value.entries.map((entry) => '${jsonEncode(entry.key)}: ${_dart(entry.value)}').join(', ')}}';

String appShell(DartloomConfig config) =>
    '''import 'package:flutter/material.dart';

import '../capabilities/capabilities.dart';

class DartloomApp extends StatelessWidget {
  const DartloomApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        title: ${jsonEncode(config.app.name)},
        localizationsDelegates: dartloomLocalizationsDelegates,
        supportedLocales: dartloomSupportedLocales,
        home: const Scaffold(body: Center(child: Text('Dartloom app'))),
      );
}
''';

const capabilityBootstrap = '''import 'package:flutter/widgets.dart';

import 'capabilities.dart';

/// Dartloom-owned startup fragment. Call this from the application's main
/// method before creating its widget tree.
Future<void> bootstrapDartloom() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDartloom();
}
''';

const agentInstructions = '''# Agent Instructions

This project is managed by Dartloom.

1. Read `dartloom.yaml` before changing infrastructure.
2. Feature code depends on capability contracts and obtains implementations with
   `Dartloom.get<T>(name: ...)`; do not import adapter packages in feature code.
3. Register app-owned implementations through `initializeDartloom` custom
   factories. Do not bypass or replace the generated registry wiring.
4. Business code belongs in `lib/features`; shared app glue belongs in `lib/app`.
5. Dartloom owns `lib/capabilities/capabilities.dart` and
   `lib/capabilities/bootstrap.dart`. Application files, including `lib/app`
   and ARB translations, are never overwritten by `dartloom project update`.

Before finishing, run `dart format .`, `flutter analyze`, and `flutter test`.
''';

const ciWorkflow = '''name: CI
on: [push, pull_request]
jobs:
  check:
    uses: wkzMagician/dartloom/.github/workflows/flutter_ci.yml@main
''';

String releaseWorkflow(DartloomConfig config) => '''name: Release
on:
  push:
    tags: ['v*']
  workflow_dispatch:
jobs:
  release:
    uses: wkzMagician/dartloom/.github/workflows/flutter_release.yml@main
    permissions:
      contents: write
    with:
      build_android: ${config.platforms.contains(TargetPlatform.android)}
      build_windows: ${config.platforms.contains(TargetPlatform.windows)}
      build_linux: ${config.platforms.contains(TargetPlatform.linux)}
''';

const l10nYaml = '''arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
''';

const appEnArb = '''{
  "@@locale": "en",
  "appTitle": "Dartloom app"
}
''';

const appZhArb = '''{
  "@@locale": "zh",
  "appTitle": "Dartloom 应用"
}
''';
