import '../capabilities/capability_registry.dart';
import '../config/dartloom_config.dart';

String capabilityGlue(Set<Capability> capabilities) {
  final localization = capabilities.contains(Capability.localization);
  return [
    '// Generated by Dartloom. Keep capability wiring here.',
    "import 'package:flutter/widgets.dart';",
    if (localization)
      "import 'package:dartloom_localization/dartloom_localization.dart';",
    '',
    for (final capability in capabilities)
      "export 'package:${CapabilityRegistry.all[capability]!.packageName}/${CapabilityRegistry.all[capability]!.packageName}.dart';",
    '',
    if (localization) ...[
      'final dartloomSupportedLocales = DartloomLocalizations.supportedLocales;',
      'final dartloomLocalizationsDelegates =',
      '    DartloomLocalizations.localizationsDelegates;',
    ] else ...[
      'const dartloomSupportedLocales = <Locale>[Locale(\'en\')];',
      'const dartloomLocalizationsDelegates =',
      '    <LocalizationsDelegate<dynamic>>[];',
    ],
    '',
  ].join('\n');
}

String appShell(DartloomConfig config) =>
    '''import 'package:flutter/material.dart';

import '../capabilities/capabilities.dart';

class DartloomApp extends StatelessWidget {
  const DartloomApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        title: '${config.app.name}',
        localizationsDelegates: dartloomLocalizationsDelegates,
        supportedLocales: dartloomSupportedLocales,
        home: const Scaffold(body: Center(child: Text('Dartloom app'))),
      );
}
''';

const agentInstructions = '''# Agent Instructions

This project is managed by Dartloom.

## Before modifying code

1. Read `dartloom.yaml`.
2. Inspect existing capabilities before implementing infrastructure.
3. Reuse existing capability packages. When `resident` is enabled, initialize
   its controller with a desktop tray icon before `runApp`.
4. Application-specific code belongs in `lib/features`.
5. Shared application glue belongs in `lib/app`.
6. Do not duplicate capability implementations.

## Before finishing

Always run:

```bash
dart format .
flutter analyze
flutter test
```

## Build and release

Do not manually create release artifacts unless explicitly requested. Release artifacts are produced by Dartloom and GitHub Actions.
''';

const ciWorkflow = '''name: CI
on: [push, pull_request]
jobs:
  check:
    uses: wkzMagician/dartloom/.github/workflows/flutter_ci.yml@main
''';

String releaseWorkflow(DartloomConfig config) => '''name: Release
on:
  push:
    tags: ['v*']
  workflow_dispatch:
jobs:
  release:
    uses: wkzMagician/dartloom/.github/workflows/flutter_release.yml@main
    permissions:
      contents: write
    with:
      build_android: ${config.platforms.contains(TargetPlatform.android)}
      build_windows: ${config.platforms.contains(TargetPlatform.windows)}
      build_linux: ${config.platforms.contains(TargetPlatform.linux)}
''';
