import '../config/dartloom_config.dart';

String appIconTest(Set<TargetPlatform> platforms) {
  final checks = <String>[];
  for (final platform in platforms) {
    final paths = switch (platform) {
      TargetPlatform.android => [
          'android/app/src/main/res/mipmap-hdpi/ic_launcher.png',
        ],
      TargetPlatform.ios => [
          'ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json',
        ],
      TargetPlatform.windows => ['windows/runner/resources/app_icon.ico'],
      TargetPlatform.macos => [
          'macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json',
        ],
      TargetPlatform.linux => ['linux/runner/resources/app_icon.png'],
      TargetPlatform.web => ['web/icons/Icon-192.png'],
    };
    for (final path in paths) {
      checks.add("    _expectFile('$path');");
    }
    if (platform == TargetPlatform.windows) {
      checks.add(
          "    _expectText('installer/windows.iss', 'SetupIconFile={#AppIconFile}');");
      checks.add(
          "    _expectText('installer/windows.iss', 'UninstallDisplayIcon={app}\\\\{#MyAppExeName}');");
    }
  }

  return '''// Generated by dartloom new. Keep this test: it verifies that the
// Flutter platform projects retain their application icon resources.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('application icons are configured for every selected platform', () {
${checks.join('\n')}
  });
}

void _expectFile(String relativePath) {
  final file = File(relativePath);
  expect(file.existsSync(), isTrue,
      reason: 'Missing application icon resource: \$relativePath');
  expect(file.lengthSync(), greaterThan(0),
      reason: 'Empty application icon resource: \$relativePath');
}

void _expectText(String relativePath, String expected) {
  final file = File(relativePath);
  expect(file.existsSync(), isTrue,
      reason: 'Missing generated installer file: \$relativePath');
  expect(file.readAsStringSync(), contains(expected),
      reason: 'Missing installer configuration in \$relativePath: \$expected');
}
''';
}
