// ignore_for_file: unnecessary_brace_in_string_interps, unnecessary_string_escapes

import '../config/dartloom_config.dart';

String windowsInstaller({
  String appName = 'Dartloom App',
  String appVersion = '0.0.0',
}) {
  final slug = _slug(appName);
  final displayName = _displayName(appName);
  return '; Generated by Dartloom. Customize this file if your installer needs extra files.\n'
      '#define MyAppName "${_escape(displayName)}"\n'
      '#ifndef MyAppVersion\n'
      '#define MyAppVersion "${_escape(appVersion)}"\n'
      '#endif\n'
      '#define MyAppExeName "${slug}.exe"\n'
      '[Setup]\n'
      'AppName={#MyAppName}\n'
      'AppVersion={#MyAppVersion}\n'
      'AppVerName={#MyAppName} {#MyAppVersion}\n'
      'DefaultDirName={autopf}\\{#MyAppName}\n'
      'OutputDir=..\\dist\n'
      'OutputBaseFilename=${slug}-{#MyAppVersion}-windows-x64-setup\n'
      'Compression=lzma2\n'
      'SolidCompression=yes\n'
      'ArchitecturesAllowed=x64compatible\n'
      'ArchitecturesInstallIn64BitMode=x64compatible\n'
      'PrivilegesRequired=lowest\n'
      '[Files]\n'
      'Source: "..\\build\\windows\\x64\\runner\\Release\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs\n'
      '[Icons]\n'
      'Name: "{autoprograms}\\{#MyAppName}"; Filename: "{app}\\{#MyAppExeName}"\n'
      '[Run]\n'
      'Filename: "{app}\\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent\n';
}

String cloudBuildWorkflow({String appName = 'dartloom_app'}) =>
    _cloudBuild(appName);

String _cloudBuild(String appName) => '''name: Dartloom Cloud Build

on:
  workflow_dispatch:
    inputs:
      platform: { required: true, type: string }
      git_ref: { required: true, type: string }
      mode: { required: true, default: release, type: string }

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      platforms: \${{ steps.set-matrix.outputs.platforms }}
    steps:
      - id: set-matrix
        run: |
          if [ "\${{ inputs.platform }}" = "all" ]; then
            echo 'platforms=["windows","linux","macos","android","ios","web"]' >> "\$GITHUB_OUTPUT"
          else
            echo 'platforms=["\${{ inputs.platform }}"]' >> "\$GITHUB_OUTPUT"
          fi

  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        platform: \${{ fromJSON(needs.matrix.outputs.platforms) }}
    runs-on: \${{ matrix.platform == 'windows' && 'windows-latest' || (matrix.platform == 'macos' || matrix.platform == 'ios') && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: \${{ inputs.git_ref }}
      - name: Install Linux build dependencies
        if: \${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev zip
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
      - run: flutter pub get
      - name: Install Windows packaging tools
        if: \${{ matrix.platform == 'windows' }}
        run: choco install innosetup --no-progress -y
      - name: Build platform
        shell: bash
        run: |
          case "\${{ matrix.platform }}" in
            android) flutter build apk --\${{ inputs.mode }} && flutter build appbundle --\${{ inputs.mode }} ;;
            ios) flutter build ios --\${{ inputs.mode }} --no-codesign ;;
            *) flutter build \${{ matrix.platform }} --\${{ inputs.mode }} ;;
          esac
      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p artifact
          app='${_slug(appName)}'
          mode='\${{ inputs.mode }}'
          case "\${{ matrix.platform }}" in
            android)
              cp "build/app/outputs/flutter-apk/app-\$mode.apk" "artifact/\${app}-android.apk"
              cp "build/app/outputs/bundle/\$mode/app-\$mode.aab" "artifact/\${app}-android.aab"
              ;;
            ios)
              mkdir -p Payload
              cp -R build/ios/iphoneos/Runner.app Payload/
              zip -qr "artifact/\${app}-ios.ipa" Payload
              ;;
            macos)
              app_path=\$(find "build/macos/Build/Products" -maxdepth 2 -name '*.app' -type d | head -n 1)
              ditto -c -k --keepParent "\$app_path" "artifact/\${app}-macos.zip"
              ;;
            windows)
              powershell -NoProfile -Command '\$version = (Select-String -Path pubspec.yaml -Pattern "^version:\\s*([0-9]+\\.[0-9]+\\.[0-9]+)").Matches.Groups[1].Value; if (-not \$version) { throw "pubspec.yaml version not found" }; & (Get-Command ISCC.exe -ErrorAction Stop).Source "/DMyAppVersion=\$version" installer\\windows.iss; Copy-Item -Path "dist\\*.exe" -Destination artifact -Force'
              ;;
            linux)
              tar -czf "artifact/\${app}-linux-x64.tar.gz" -C "build/linux/x64/\$mode" bundle
              ;;
            web)
              (cd build/web && zip -qr "../../artifact/\${app}-web.zip" .)
              ;;
          esac
          printf '{"schema_version":1,"platform":"%s","commit":"%s","files":[]}' "\${{ matrix.platform }}" "\${{ github.sha }}" > artifact/dartloom-build.json
      - uses: actions/upload-artifact@v4
        with:
          name: dartloom-\${{ matrix.platform }}
          path: artifact
''';

String ciWorkflow() => '''name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
''';

String releaseWorkflow(DartloomConfig config,
    {String appName = 'dartloom_app'}) {
  final jobs =
      config.platforms.map((platform) => _releaseJob(platform, appName));
  final needs = config.platforms.map((platform) => platform.name).join(', ');
  return '''name: Release

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
${jobs.join('\n')}
  release:
    needs: [$needs]
    if: \${{ startsWith(github.ref, 'refs/tags/v') && !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: downloaded_artifacts
      - name: Collect release files
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p release_files
          find downloaded_artifacts -type f ! -name 'dartloom-build.json' -exec cp {} release_files/ \\;
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          overwrite_files: true
          files: release_files/*
''';
}

String _releaseJob(TargetPlatform platform, String appName) {
  final slug = _slug(appName);
  final runner = switch (platform) {
    TargetPlatform.android ||
    TargetPlatform.linux ||
    TargetPlatform.web =>
      'ubuntu-latest',
    TargetPlatform.ios || TargetPlatform.macos => 'macos-latest',
    TargetPlatform.windows => 'windows-latest',
  };
  final linuxDependencies = platform == TargetPlatform.linux
      ? '''      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev zip
'''
      : '';
  final windowsInstall = platform == TargetPlatform.windows
      ? '      - run: choco install innosetup --no-progress -y\n'
      : '';
  final build = switch (platform) {
    TargetPlatform.android =>
      '      - run: flutter build apk --release\n      - run: flutter build appbundle --release',
    TargetPlatform.ios =>
      '      - run: flutter build ios --release --no-codesign',
    TargetPlatform.macos => '      - run: flutter build macos --release',
    TargetPlatform.windows => '      - run: flutter build windows --release',
    TargetPlatform.linux => '      - run: flutter build linux --release',
    TargetPlatform.web => '      - run: flutter build web --release',
  };
  final package = switch (platform) {
    TargetPlatform.android => '''      - name: Package Android
        shell: bash
        run: |
          mkdir -p dist
          cp build/app/outputs/flutter-apk/app-release.apk dist/${slug}-android.apk
          cp build/app/outputs/bundle/release/app-release.aab dist/${slug}-android.aab
''',
    TargetPlatform.ios => '''      - name: Package iOS IPA
        shell: bash
        run: |
          mkdir -p dist Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -qr dist/${slug}-ios.ipa Payload
''',
    TargetPlatform.macos => '''      - name: Package macOS app
        shell: bash
        run: |
          mkdir -p dist
          app_path=\$(find build/macos/Build/Products/Release -maxdepth 1 -name '*.app' -type d | head -n 1)
          ditto -c -k --keepParent "\$app_path" dist/${slug}-macos.zip
''',
    TargetPlatform.windows => '''      - name: Package Windows installer
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist
          \$version = (Select-String -Path pubspec.yaml -Pattern '^version:\\s*([0-9]+\\.[0-9]+\\.[0-9]+)').Matches.Groups[1].Value
          if (-not \$version) { throw "pubspec.yaml version not found" }
          & (Get-Command ISCC.exe -ErrorAction Stop).Source "/DMyAppVersion=\$version" installer\\windows.iss
''',
    TargetPlatform.linux => '''      - name: Package Linux bundle
        shell: bash
        run: |
          mkdir -p dist
          tar -czf dist/${slug}-linux-x64.tar.gz -C build/linux/x64/release bundle
''',
    TargetPlatform.web => '''      - name: Package Web
        shell: bash
        run: |
          mkdir -p dist
          (cd build/web && zip -qr ../../dist/${slug}-web.zip .)
''',
  };
  final artifact = platform == TargetPlatform.windows ? 'dist/*.exe' : 'dist/*';
  return '''  ${platform.name}:
    runs-on: $runner
    steps:
      - uses: actions/checkout@v4
${linuxDependencies}      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
      - run: flutter pub get
${windowsInstall}$build
$package      - uses: actions/upload-artifact@v4
        with:
          name: ${platform.name}
          path: $artifact
''';
}

String _slug(String value) {
  final slug = value
      .trim()
      .replaceAll(RegExp(r'[^A-Za-z0-9_-]+'), '_')
      .replaceAll(RegExp(r'_+'), '_');
  return slug.isEmpty ? 'dartloom_app' : slug.toLowerCase();
}

String _displayName(String value) => value
    .replaceAll(RegExp(r'[_-]+'), ' ')
    .split(' ')
    .where((part) => part.isNotEmpty)
    .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
    .join(' ');

String _escape(String value) => value.replaceAll('"', '""');
