name: dartloom_pairing
description: Generic device identity and pairing capability for Dartloom.
version: 0.1.0
repository: https://github.com/wkzMagician/dartloom
environment:
  sdk: ^3.13.0
  flutter: '>=3.22.0'
dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.10
  qr_flutter: ^4.1.0
  multicast_dns: ^0.3.3+1
dev_dependencies:
  test: ^1.26.0


